### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Bloodlex** [AlonsoAliaga/BetterHeads#2] opened 2021-05-29 16:42 UTC
**Describe the bug**
Plugin is not enabled on startup with a following exception:

```
[04:00:42] [Server thread/INFO]: [BetterHeads] Loading 36950 heads from heads.yml.. This is a huge amount of heads.
[04:00:42] [Server thread/INFO]: [BetterHeads] This process can take a while, please be patient.
[04:00:42] [Server thread/ERROR]: Error occurred while enabling BetterHeads v1.2-BETA (Is it up to date?)
java.lang.IllegalArgumentException: UUID string too large
	at java.util.UUID.fromString(UUID.java:199) ~[?:?]
	at com.alonsoaliaga.betterheads.BetterHeads.loadCurrentDatabaseHeads(BetterHeads.java:333) ~[?:?]
	at com.alonsoaliaga.betterheads.BetterHeads.startUpLoadHeads(BetterHeads.java:291) ~[?:?]
	at com.alonsoaliaga.betterheads.BetterHeads.onEnable(BetterHeads.java:151) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1060]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1070) ~[patched_1.16.5.jar:git-Purpur-1060]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1060]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[04:00:42] [Server thread/INFO]: [BetterHeads] Disabling BetterHeads v1.2-BETA
[04:00:42] [Server thread/INFO]:  
[04:00:42] [Server thread/INFO]: [BetterHeads] Plugin has been disabled!
[04:00:42] [Server thread/INFO]: [BetterHeads] Thank you for using my plugin!
```

Unfortunately, I don't have any clue what can be the reason for that 🙁 . I don't know which UUID is mentioned here and what's going on.

**To Reproduce**
1. Start the server with this plugin.
2. Exception on startup

**Expected behavior**
The plugin should start.

**Important (please complete the following information):**
 - Java version: 11
 - Plugin version: 1.2-BETA
 - Server version: Purpur version git-Purpur-1060 (MC: 1.16.5)

**Additional context**
The problem showed up suddenly and I have no idea what can be the cause of that unfortunately 😢 . Here is a list of my other plugins, maybe this will be helpful:

Plugins (60): ActionHealth*, AdvancedLogger*, AdvancedRegionMarket, AntiWorldFly, ArmShopBridge, AsyncWorldEdit, AuthMe, BetterHeads, ChestSort, CommandNotifier, CommandPanels, CraftBook, DeathPenalties, dynmap*, Dynmap-WorldGuard*, EasyCarts, Epidemic, Essentials, EssentialsChat, GoldenEnchants, GSit, Harbor, HolographicDisplays, Images, Jobs, KeepChunks, LangUtils, LocaleLib, LogBlock, LuckPerms, LWC, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, OpenInv, OreAnnouncer, PetMaster, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QuickShop, QuickShopDynmap, QuickShopList, RegionRaid, SkinsRestorer, Spartan, StackMob, SuperVanish, TAB, TitleManager, TreeAssist, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by AlonsoAliaga** [comment] 2021-05-29 16:45
Error was made by the API (author) we use to grab the heads. Rename heads.yml and let it regenerate again. This issue was not caused by our plugin code, however in the next update we will add a check to prevent this from happening again 😁

**Comment by Bloodlex** [comment] 2021-05-29 19:08
> Error was made by the API (author) we use to grab the heads. Rename heads.yml and let it regenerate again. This issue was not caused by our plugin code, however in the next update we will add a check to prevent this from happening again 😁

I see 🙂 Do you know perhaps if there is any way I can save my current heads? I have quite a lot of them on the server und it would be nice not to have place all of them once again 😂 And if I generate a new file I will lose all of them... 🙁

**Comment by AlonsoAliaga** [comment] 2021-05-29 19:13
Go to your heads.yml and search the word "3Storage", then from that UUID remove ONLY "Storage" without the 3, save and restart the server. Should work now, if not, means that there is probably another issue

**Comment by AlonsoAliaga** [comment] 2021-06-01 19:50
Issue marked as solved. Next update will have an additional check in case API managers made a mistake again.

**Closed as completed by AlonsoAliaga** 2021-06-01 19:50 UTC
Labels: Solved
